[package]
name = "cobalt-aws"
version = "0.6.0"
authors = ["harrison.ai Data Engineering <dataengineering@harrison.ai>"]
edition = "2021"
description = "This library provides a collection of wrappers around the aws-sdk-rust and lambda_runtime packages."
repository = "https://github.com/harrison-ai/cobalt-aws/"
license = "Apache-2.0"
publish = true
include = [
    "Cargo.toml",
    "src/*",
    "README.md",
    "CHANGELOG.md",
    "LICENCE",
    "licenses/licenses.html",
]

[dependencies]
anyhow = "1.0.58"
async-trait = "0.1.56"
aws-config = "0.46.0"
aws-sdk-athena = "0.16.0"
aws-sdk-s3 = "0.16.0"
aws-sdk-sqs = "0.16.0"
aws-smithy-http = "0.46.0"
aws-types = "0.46.0"
aws_lambda_events = "0.6.3"
clap = { version = "3.2.16", features = ["derive", "env"] }
futures = "0.3.21"
http = "0.2.8"
lambda_runtime = "0.6.0"
serde = "1.0.140"
serde_json = "1.0.82"
tokio = { version = "1.20.1", features=["macros"] }
tracing = "0.1.35"
tracing-subscriber = { version = "0.3.15", features=["json", "env-filter"] }

[dev-dependencies]
reqwest = { version = "0.11.11", features=["json"] }
serial_test = "0.8.0"
tokio-test = "0.4.2"
