[package]
name = "cobalt-aws"
version = "0.3.0"
authors = ["harrison.ai Data Engineering <dataengineering@harrison.ai>"]
edition = "2021"
description = "This library provides a collection of wrappers around the aws-sdk-rust and lambda_runtime packages."
repository = "https://github.com/harrison-ai/cobalt-aws/"
license = "Apache-2.0"
publish = true
include = [
    "Cargo.toml",
    "src/*",
    "README.md",
    "CHANGELOG.md",
    "LICENCE",
]

[dependencies]
anyhow = "1.0.56"
async-trait = "0.1.52"
aws-config = "0.8.0"
aws-sdk-athena = "0.8.0"
aws-sdk-s3 = "0.8.0"
aws-sdk-sqs = "0.8.0"
aws_lambda_events = "0.6.1"
clap = { version = "3.1.6", features = ["derive", "env"] }
futures = "0.3.21"
http = "0.2.6"
lambda_runtime = "0.5.0"
serde = "1.0.136"
serde_json = "1.0.79"
tokio = { version = "1.17.0", features=["macros"] }
tracing = "0.1.31"
tracing-subscriber = { version = "0.3.9", features=["json", "env-filter"] }

[dev-dependencies]
reqwest = { version = "0.11.9", features=["json"] }
serial_test = "0.6.0"
tokio-test = "0.4.2"
