[package]
name = "cobalt-aws"
version = "0.11.1"
authors = ["harrison.ai Data Engineering <dataengineering@harrison.ai>"]
edition = "2021"
description = "This library provides a collection of wrappers around the aws-sdk-rust and lambda_runtime packages."
repository = "https://github.com/harrison-ai/cobalt-aws/"
license = "Apache-2.0"
publish = true
include = [
    "Cargo.toml",
    "src/*",
    "README.md",
    "CHANGELOG.md",
    "LICENCE",
    "licenses/licenses.html",
]

[dependencies]
anyhow = "1.0.72"
async-trait = "0.1.71"
aws-config = "0.56.0"
aws-sdk-athena = "0.29.0"
aws-sdk-s3 = "0.29.0"
aws-sdk-sqs = "0.29.0"
aws-smithy-http = "0.56.0"
aws-types = "0.56.0"
aws_lambda_events = { version = "0.10.0", default-features=false, features = ["sqs"]}
lambda_runtime = "0.8.1"
bytesize = "1.2.0"
clap = { version = "4.3.17", features = ["derive", "env"] }
derivative = "2.2.0"
futures = "0.3.28"
http = "0.2.9"
serde = "1.0.188"
serde_json = "1.0.103"
tokio = { version = "1.29.1", features=["macros"] }
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.17", features=["json", "env-filter"] }
url = { version = "2.4.0", features = ["serde"] }

[dev-dependencies]
function_name = "0.3.0"
rand = "0.8.5"
rand_chacha = "0.3.1"
reqwest = { version = "0.11.18", features=["json"] }
serial_test = "2.0.0"
tokio-test = "0.4.2"
