[package]
name = "cobalt-aws"
version = "0.4.0"
authors = ["harrison.ai Data Engineering <dataengineering@harrison.ai>"]
edition = "2021"
description = "This library provides a collection of wrappers around the aws-sdk-rust and lambda_runtime packages."
repository = "https://github.com/harrison-ai/cobalt-aws/"
license = "Apache-2.0"
publish = true
include = [
    "Cargo.toml",
    "src/*",
    "README.md",
    "CHANGELOG.md",
    "LICENCE",
]

[dependencies]
anyhow = "1.0.57"
async-trait = "0.1.53"
aws-config = "0.9.0"
aws-sdk-athena = "0.9.0"
aws-sdk-s3 = "0.9.0"
aws-sdk-sqs = "0.9.0"
aws-types = "0.9.0"
aws_lambda_events = "0.6.2"
clap = { version = "3.1.14", features = ["derive", "env"] }
futures = "0.3.21"
http = "0.2.7"
lambda_runtime = "0.5.1"
serde = "1.0.137"
serde_json = "1.0.80"
tokio = { version = "1.18.0", features=["macros"] }
tracing = "0.1.34"
tracing-subscriber = { version = "0.3.11", features=["json", "env-filter"] }

[dev-dependencies]
reqwest = { version = "0.11.10", features=["json"] }
serial_test = "0.6.0"
tokio-test = "0.4.2"
