[package]
name = "cobalt-aws"
version = "0.9.1"
authors = ["harrison.ai Data Engineering <dataengineering@harrison.ai>"]
edition = "2021"
description = "This library provides a collection of wrappers around the aws-sdk-rust and lambda_runtime packages."
repository = "https://github.com/harrison-ai/cobalt-aws/"
license = "Apache-2.0"
publish = true
include = [
    "Cargo.toml",
    "src/*",
    "README.md",
    "CHANGELOG.md",
    "LICENCE",
    "licenses/licenses.html",
]

[dependencies]
anyhow = "1.0.66"
async-trait = "0.1.58"
aws-config = "0.51.0"
aws-sdk-athena = "0.21.0"
aws-sdk-s3 = "0.21.0"
aws-sdk-sqs = "0.21.0"
aws-smithy-http = "0.51.0"
aws-types = "0.51.0"
aws_lambda_events = "0.7.2"
bytesize = "1.1.0"
clap = { version = "4.0.29", features = ["derive", "env"] }
derivative = "2.2.0"
futures = "0.3.25"
http = "0.2.8"
lambda_runtime = "0.7.1"
serde = "1.0.148"
serde_json = "1.0.89"
tokio = { version = "1.22.0", features=["macros"] }
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.16", features=["json", "env-filter"] }
url = { version = "2.3.1", features = ["serde"] }

[dev-dependencies]
function_name = "0.3.0"
rand = "0.8.5"
rand_chacha = "0.3.1"
reqwest = { version = "0.11.13", features=["json"] }
serial_test = "0.9.0"
tokio-test = "0.4.2"
