[package]
name = "cobalt-aws"
version = "0.1.0"
authors = ["harrison.ai Data Engineering <dataengineering@harrison.ai>"]
edition = "2021"
description = "This library provides a collection of wrappers around the aws-sdk-rust packages."
repository = "https://github.com/harrison-ai/cobalt-aws/"
license = "Apache-2.0"
publish = true
include = [
    "Cargo.toml",
    "src/*",
    "README.md",
    "CHANGELOG.md",
    "LICENCE",
]


[dependencies]
anyhow = "1.0.54"
aws-config = "0.6.0"
aws-sdk-s3 = "0.6.0"
http = "0.2.6"
tokio = { version = "1.16.1", features=["macros"] }

[dev-dependencies]
serial_test = "0.6.0"
tokio-test = "0.4.2"
