# See https://embarkstudios.github.io/cargo-deny/cli/init.html
# for details on these configuration options.

[advisories]
vulnerability = "deny"
unmaintained = "warn"
yanked = "warn"
notice = "warn"
ignore = [
    # time/chrono problems, have not been a problem in practice
    "RUSTSEC-2020-0071",
]

[licenses]
default = "deny"
unlicensed = "deny"
copyleft = "deny"
allow = [
    "MIT",
    "Apache-2.0",
    # You can safely enable these licenses if needed:
    "BSD-3-Clause",
    "ISC",
    "OpenSSL",
    "Unicode-DFS-2016",
]

# The `ring` crate has a complicated license situation with different licenses
# for different parts of the codebase, but they're all acceptable to us.
# If you need the `ring` crate then uncomment the below.
[[licenses.clarify]]
name = "ring"
version = "*"
expression = "MIT AND ISC AND OpenSSL"
license-files = [
    { path = "LICENSE", hash = 0xbd0eed23 }
]

# https://github.com/hsivonen/encoding_rs#licensing
[[licenses.clarify]]
name = "encoding_rs"
version = "*"
expression = "(Apache-2.0 OR MIT) AND BSD-3-Clause"
license-files = [
    { path = "COPYRIGHT", hash = 0x39f8ad31 }
]

[licenses.private]
# So we don't have to declare a license on our own unpublished crates.
ignore = true

[bans]
multiple-versions = "warn"
wildcards = "warn"

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-git = []
