services:

  cargo:
    image: ghcr.io/harrison-ai/rust:1.89-0.0
    entrypoint: cargo
    volumes:
      - '~/.cargo/registry:/usr/local/cargo/registry'
      - '.:/app'
    working_dir: '/app'
    environment:
      - LOCALSTACK_HOSTNAME=localstack
      - AWS_DEFAULT_REGION=ap-southeast-2
      - AWS_ACCESS_KEY_ID=placeholder
      - AWS_SECRET_ACCESS_KEY=placeholder
        #- RUST_LOG=debug
        #- RUST_BACKTRACE=full
    depends_on:
      localstack:
        condition: service_healthy

  awslocal:
    build:
      context: scripts
      dockerfile: Dockerfile-awslocal
    entrypoint: awslocal
    volumes:
      - '.:/app'
    working_dir: '/app'
    environment:
      - LOCALSTACK_HOST=localstack
      - AWS_DEFAULT_REGION=ap-southeast-2
      - AWS_ACCESS_KEY_ID=placeholder
      - AWS_SECRET_ACCESS_KEY=placeholder
      - AWS_PAGER=""
    depends_on:
      - localstack

  localstack:
    image: localstack/localstack:4.8.1
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack-main}"
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      - DEBUG=${DEBUG-}
      - PERSISTENCE=${PERSISTENCE-}
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR-}
      - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY-}  # only required for Pro
      - DOCKER_HOST=unix:///var/run/docker.sock
      - AWS_DEFAULT_REGION=ap-southeast-2
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./scripts/init-localstack.sh:/etc/localstack/init/ready.d/init-aws.sh"
      - "./test-data:/tmp/test-data"
    healthcheck:
      test:
        - CMD
        - bash
        - -c
        - awslocal s3 ls
      interval: 2s
      timeout: 10s
      start_period: 5s
