version: '3.7'
services:

  cargo:
    image: harrisonai/rust:1.60-0.2
    entrypoint: cargo
    volumes:
      - '~/.cargo/registry:/usr/local/cargo/registry'
      - '.:/app'
    working_dir: '/app'
    environment:
      - LOCALSTACK_HOSTNAME=localstack
      - AWS_DEFAULT_REGION=ap-southeast-2
      - AWS_ACCESS_KEY_ID=placeholder
      - AWS_SECRET_ACCESS_KEY=placeholder
    depends_on:
      - localstack

  localstack:
    image: localstack/localstack:0.14.4
    ports:
      - "4566:4566"
    environment:
      - SERVICES=${SERVICES-}
      - DEBUG=0
      - DATA_DIR=${DATA_DIR-}
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR-}
      - HOST_TMP_FOLDER=${TMPDIR:-/tmp/}localstack
      - DOCKER_HOST=unix:///var/run/docker.sock
      - AWS_DEFAULT_REGION=ap-southeast-2
    volumes:
      - "${TMPDIR:-/tmp}/localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./scripts/init-localstack.sh:/docker-entrypoint-initaws.d/init-localstack.sh"
      - "./test-data:/tmp/test-data"
