# Docker image used for running `awslocal`

FROM python:3.13-slim-bullseye

RUN apt-get update && \
    apt-get install --yes --quiet --no-install-recommends \
        ca-certificates \
        groff \
        python-dev \
        curl \
        wget \
        unzip \
        less
RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && \
    unzip awscliv2.zip && \
    ./aws/install && \
    rm awscliv2.zip && \
    rm -rf ./aws/

RUN pip install awscli-local
